### PR TITLE
Update for kernel 4.4.1

### PR DESCRIPTION
**Pull request by sempervictus**
Probably not the neatest thing ever done, but hasn't caused me any problems on 4.4.1.

### CODE REVIEW

**Comment by sempervictus** [comment]
On 4.4.6 now and i dont believe i've made any new changes, still using it daily.

**Comment by chilek** [comment]
@sempervictus you've missed changes in **gre_demux.c** in patches for 4.4 series.
Fortunately they port easily from 3.15 series :smile:

**Comment by sempervictus** [comment]
Yike. My current set works fine for 4.6, I'll push those in a bit. Thanks
for the heads up

**Comment by chilek** [comment]
EOIP patch as single file for 4.4 series below:
[linux-4.4.6-eoip.patch.zip](https://github.com/bbonev/eoip/files/390716/linux-4.4.6-eoip.patch.zip)

**Comment by chilek** [comment]
@sempervictus btw. do you know if routeros already supports gretap tunnels?

**Comment by BytEvil** [comment]
@chilek your patch worked fine under ArchLinux kernel 4.4.19-1-lts. Thanks!

**Comment by work40** [comment]
**@chilek**, this patch is not compatible with 4.14 kernel (tested on 4.14.30-lts).
```
CC [M]  net/ipv4/eoip.o
net/ipv4/eoip.c:63:0: warning: "HASH_SIZE" redefined
 #define HASH_SIZE 16

In file included from ./include/linux/netdevice.h:53:0,
                 from net/ipv4/eoip.c:23:
./include/linux/hashtable.h:27:0: note: this is the location of the previous definition
 #define HASH_SIZE(name) (ARRAY_SIZE(name))

net/ipv4/eoip.c: In function 'eoip_setup':
net/ipv4/eoip.c:763:7: error: 'struct net_device' has no member named 'destructor'; did you mean 'priv_destructor'?
  dev->destructor = eoip_dev_free;
       ^~~~~~~~~~
       priv_destructor
net/ipv4/eoip.c: At top level:
net/ipv4/eoip.c:896:14: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .validate = eoip_validate,
              ^~~~~~~~~~~~~
net/ipv4/eoip.c:896:14: note: (near initialization for 'eoip_ops.validate')
net/ipv4/eoip.c:897:13: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .newlink = eoip_newlink,
             ^~~~~~~~~~~~
net/ipv4/eoip.c:897:13: note: (near initialization for 'eoip_ops.newlink')
net/ipv4/eoip.c:898:16: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .changelink = eoip_changelink,
                ^~~~~~~~~~~~~~~
net/ipv4/eoip.c:898:16: note: (near initialization for 'eoip_ops.changelink')
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:335: net/ipv4/eoip.o] Error 1
make[1]: *** [scripts/Makefile.build:587: net/ipv4] Error 2
make: *** [Makefile:1031: net] Error 2
```

**Pull request closed without merging**
